In [1]:
import time

import matplotlib.pyplot as plt 
import numpy as np 
import os 
import pandas as pd 
import seaborn as sns

In [2]:
train_images = np.load("Kannada_MNIST_npz/Kannada_MNIST/X_kannada_MNIST_train.npz")['arr_0']
test_images = np.load("Kannada_MNIST_npz/Kannada_MNIST/X_kannada_MNIST_test.npz")['arr_0']
train_labels = np.load("Kannada_MNIST_npz/Kannada_MNIST/y_kannada_MNIST_train.npz")['arr_0']
test_labels = np.load("Kannada_MNIST_npz/Kannada_MNIST/y_kannada_MNIST_test.npz")['arr_0']

In [3]:
top_left_train = train_images[:,0:14,0:14]
top_right_train = train_images[:,0:14,14:28]
bot_left_train = train_images[:,14:28,0:14]
bot_right_train = train_images[:,14:28,14:28]

In [4]:
top_left_test = test_images[:,0:14,0:14]
top_right_test = test_images[:,0:14,14:28]
bot_left_test = test_images[:,14:28,0:14]
bot_right_test = test_images[:,14:28,14:28]

In [5]:
import tensorflow.keras as keras
from keras.models import Sequential
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.layers.core import Activation
from keras.layers.core import Dropout
from keras.layers.core import Dense
from keras.layers.core import Flatten
from tensorflow.keras import backend as K

Using TensorFlow backend.


In [6]:
img_rows, img_cols = 28, 28
batch_size = 128
num_classes = 10
epochs = 10

In [7]:
x_train = np.expand_dims(train_images, axis=-1)
top_left_x_train = np.expand_dims(top_left_train, axis=-1)
top_right_x_train = np.expand_dims(top_right_train, axis=-1)
bot_left_x_train = np.expand_dims(bot_left_train, axis=-1)
bot_right_x_train = np.expand_dims(bot_right_train, axis=-1)

x_test = np.expand_dims(test_images, axis=-1)
top_left_x_test = np.expand_dims(top_left_test, axis=-1)
top_right_x_test = np.expand_dims(top_right_test, axis=-1)
bot_left_x_test = np.expand_dims(bot_left_test, axis=-1)
bot_right_x_test = np.expand_dims(bot_right_test, axis=-1)

y_train = keras.utils.to_categorical(train_labels)
y_test = keras.utils.to_categorical(test_labels)
images = np.load("Kannada_MNIST_npz/Dig_MNIST/X_dig_MNIST.npz")['arr_0']
labels = np.load("Kannada_MNIST_npz/Dig_MNIST/y_dig_MNIST.npz")['arr_0']

In [8]:
top_left_digi = images[:,0:14,0:14]
top_right_digi = images[:,0:14,14:28]
bot_left_digi = images[:,14:28,0:14]
bot_right_digi = images[:,14:28,14:28]

In [9]:
x_digi_test = np.expand_dims(images, axis=-1)
top_left_x_digi_test = np.expand_dims(top_left_digi, axis=-1)
top_right_x_digi_test = np.expand_dims(top_right_digi, axis=-1)
bot_left_x_digi_test = np.expand_dims(bot_left_digi, axis=-1)
bot_right_x_digi_test = np.expand_dims(bot_right_digi, axis=-1)

y_digi_test = keras.utils.to_categorical(labels)

In [10]:
model_main = Sequential()
model_main.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(img_rows, img_cols, 1)))
model_main.add(Conv2D(64, (3, 3), activation='relu'))
model_main.add(MaxPooling2D(pool_size=(2, 2)))
model_main.add(Dropout(0.25))
model_main.add(Conv2D(64, (3, 3), activation='relu'))
model_main.add(MaxPooling2D(pool_size=(2, 2)))
model_main.add(Dropout(0.25))
model_main.add(Conv2D(64, (3, 3), activation='relu'))
model_main.add(MaxPooling2D(pool_size=(2, 2)))
model_main.add(Dropout(0.25))
model_main.add(Flatten())



model_quat = Sequential()
model_quat.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(img_rows/2, img_cols/2, 1)))
model_quat.add(Conv2D(64, (3, 3), activation='relu'))
model_quat.add(MaxPooling2D(pool_size=(2, 2)))
model_quat.add(Dropout(0.25))
model_quat.add(Conv2D(64, (3, 3), activation='relu'))
model_quat.add(MaxPooling2D(pool_size=(2, 2)))
model_quat.add(Dropout(0.25))
model_quat.add(Flatten())






Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [11]:
main_features = model_main.predict(x_train)
top_left_features = model_quat.predict(top_left_x_train)
top_right_features = model_quat.predict(top_right_x_train)
bot_left_features = model_quat.predict(bot_left_x_train)
bot_right_features = model_quat.predict(bot_right_x_train)

total_train_features = np.concatenate((main_features, top_left_features, top_right_features
               , bot_left_features, bot_right_features), axis=1)

In [12]:
main_features = model_main.predict(x_test)
top_left_features = model_quat.predict(top_left_x_test)
top_right_features = model_quat.predict(top_right_x_test)
bot_left_features = model_quat.predict(bot_left_x_test)
bot_right_features = model_quat.predict(bot_right_x_test)

total_test_features = np.concatenate((main_features, top_left_features, top_right_features
               , bot_left_features, bot_right_features), axis=1)

In [13]:
main_features = model_main.predict(x_digi_test)
top_left_features = model_quat.predict(top_left_x_digi_test)
top_right_features = model_quat.predict(top_right_x_digi_test)
bot_left_features = model_quat.predict(bot_left_x_digi_test)
bot_right_features = model_quat.predict(bot_right_x_digi_test)

total_digi_features = np.concatenate((main_features, top_left_features, top_right_features
               , bot_left_features, bot_right_features), axis=1)

In [14]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

scaler = StandardScaler()
mscaler = MinMaxScaler()
x_train = mscaler.fit_transform(total_train_features)#np.expand_dims(dct_train, axis=-1)
x_test = mscaler.fit_transform(total_test_features)#np.expand_dims(dct_test, axis=-1)
x_digi_test = mscaler.fit_transform(total_digi_features)#np.expand_dims(dct_digi, axis=-1)

y_train = train_labels#keras.utils.to_categorical(train_labels)
y_test = test_labels#keras.utils.to_categorical(test_labels)
y_digi_test = labels#keras.utils.to_categorical(digi_labels)

In [15]:
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='sigmoid') # Linear Kernel

#Train the model using the training sets
clf.fit(x_train, y_train)

#Predict the response for test dataset
y_test_pred = clf.predict(x_test)
y_digi_pred = clf.predict(x_digi_test)

/home/daniel/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


from keras.layers import Input
from keras.models import Model
from keras.layers import concatenate


input_main = Input(shape=(img_rows, img_cols, 1))
input_top_left = Input(shape=(img_rows/2, img_cols/2, 1))
input_top_right = Input(shape=(img_rows/2, img_cols/2, 1))
input_bot_left = Input(shape=(img_rows/2, img_cols/2, 1))
input_bot_right = Input(shape=(img_rows/2, img_cols/2, 1))

x_main = Conv2D(32, kernel_size=(3, 3), activation="relu")(input_main)
x_main = Conv2D(64, (3, 3), activation='relu')(x_main)
x_main = MaxPooling2D(pool_size=(2, 2))(x_main)
x_main = Dropout(0.25)(x_main)
x_main = Conv2D(64, (3, 3), activation='relu')(x_main)
x_main = MaxPooling2D(pool_size=(2, 2))(x_main)
x_main = Dropout(0.25)(x_main)
x_main = Flatten()(x_main)
x_main = Model(inputs = input_main,outputs = x_main)

x_top_left = Conv2D(32, kernel_size=(3, 3), activation="relu")(input_top_left)
x_top_left = Conv2D(64, (3, 3), activation='relu')(x_top_left)
x_top_left = MaxPooling2D(pool_size=(2, 2))(x_top_left)
x_top_left = Dropout(0.25)(x_top_left)
x_top_left = Conv2D(64, (3, 3), activation='relu')(x_top_left)
x_top_left = MaxPooling2D(pool_size=(2, 2))(x_top_left)
x_top_left = Dropout(0.25)(x_top_left)
x_top_left = Flatten()(x_top_left)
x_top_left = Model(inputs = input_top_left,outputs = x_top_left)

x_top_right = Conv2D(32, kernel_size=(3, 3), activation="relu")(input_top_right)
x_top_right = Conv2D(64, (3, 3), activation='relu')(x_top_right)
x_top_right = MaxPooling2D(pool_size=(2, 2))(x_top_right)
x_top_right = Dropout(0.25)(x_top_right)
x_top_right = Conv2D(64, (3, 3), activation='relu')(x_top_right)
x_top_right = MaxPooling2D(pool_size=(2, 2))(x_top_right)
x_top_right = Dropout(0.25)(x_top_right)
x_top_right = Flatten()(x_top_right)
x_top_right = Model(inputs = input_top_right,outputs = x_top_right)

x_bot_left = Conv2D(32, kernel_size=(3, 3), activation="relu")(input_bot_left)
x_bot_left = Conv2D(64, (3, 3), activation='relu')(x_bot_left)
x_bot_left = MaxPooling2D(pool_size=(2, 2))(x_bot_left)
x_bot_left = Dropout(0.25)(x_bot_left)
x_bot_left = Conv2D(64, (3, 3), activation='relu')(x_bot_left)
x_bot_left = MaxPooling2D(pool_size=(2, 2))(x_bot_left)
x_bot_left = Dropout(0.25)(x_bot_left)
x_bot_left = Flatten()(x_bot_left)
x_bot_left = Model(inputs = input_bot_left,outputs = x_bot_left)

x_bot_right = Conv2D(32, kernel_size=(3, 3), activation="relu")(input_bot_right)
x_bot_right = Conv2D(64, (3, 3), activation='relu')(x_bot_right)
x_bot_right = MaxPooling2D(pool_size=(2, 2))(x_bot_right)
x_bot_right = Dropout(0.25)(x_bot_right)
x_bot_right = Conv2D(64, (3, 3), activation='relu')(x_bot_right)
x_bot_right = MaxPooling2D(pool_size=(2, 2))(x_bot_right)
x_bot_right = Dropout(0.25)(x_bot_right)
x_bot_right = Flatten()(x_bot_right)
x_bot_right = Model(inputs = input_bot_right,outputs = x_bot_right)


combined = concatenate([x_main.output, x_top_left.output, x_top_right.output,
                        x_bot_left.output, x_bot_right.output], axis=1)

z = Dense(50, activation="relu")(combined)
z = Dense(num_classes, activation = 'softmax')(z)

model = Model(inputs = [x_main.input, x_top_left.input, x_top_right.input,
                        x_bot_left.input, x_bot_right.input], outputs = z)

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adam(),
              metrics=['accuracy'])

model.fit([x_train,top_left_x_train,top_right_x_train,bot_left_x_train,bot_right_x_train], y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
        )

In [17]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

#y_digi_pred = model.predict(x_digi_test, batch_size=32, verbose=1)
predicted = y_digi_pred#np.argmax(pred, axis=1)
report = classification_report(y_digi_test, predicted, digits = 4)
confusion_matrix = confusion_matrix(y_true=y_digi_test, y_pred=predicted)
print(report)
print(confusion_matrix)

              precision    recall  f1-score   support

           0     0.6162    0.3262    0.4266      1024
           1     0.7898    0.4990    0.6116      1024
           2     0.6208    0.8730    0.7256      1024
           3     0.6549    0.2539    0.3659      1024
           4     0.7904    0.5449    0.6451      1024
           5     0.4293    0.8301    0.5659      1024
           6     0.5281    0.5781    0.5520      1024
           7     0.6688    0.4102    0.5085      1024
           8     0.4602    0.8008    0.5845      1024
           9     0.7292    0.7100    0.7194      1024

    accuracy                         0.5826     10240
   macro avg     0.6288    0.5826    0.5705     10240
weighted avg     0.6288    0.5826    0.5705     10240

[[334  71  95  23   8  55  46  23 309  60]
 [112 511 127   8  16 102  19  10  99  20]
 [ 14   8 894   5  20  48  11   5  14   5]
 [ 25   2 135 260   5 488  47  43  12   7]
 [  5   2  23  43 558 102   4   7 172 108]
 [  1   0  10   2   5 850 

In [18]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

#y_test_pred = model.predict(x_test, batch_size=32, verbose=1)
predicted = y_test_pred#np.argmax(pred, axis=1)
report = classification_report(y_test, predicted, digits = 4)
confusion_matrix = confusion_matrix(y_true=y_test, y_pred=predicted)
print(report)
print(confusion_matrix)

              precision    recall  f1-score   support

           0     0.9020    0.8100    0.8535      1000
           1     0.8417    0.9040    0.8717      1000
           2     0.9940    0.9910    0.9925      1000
           3     0.8267    0.8870    0.8558      1000
           4     0.8015    0.9530    0.8707      1000
           5     0.9580    0.8660    0.9097      1000
           6     0.8991    0.9270    0.9129      1000
           7     0.9196    0.7890    0.8493      1000
           8     0.9566    0.9470    0.9518      1000
           9     0.9635    0.9500    0.9567      1000

    accuracy                         0.9024     10000
   macro avg     0.9063    0.9024    0.9025     10000
weighted avg     0.9063    0.9024    0.9025     10000

[[810 144   0  35   3   0   1   1   5   1]
 [ 25 904   2  49   6   6   0   0   3   5]
 [  4   1 991   0   2   1   1   0   0   0]
 [ 12   2   3 887  21  14  10  51   0   0]
 [  0   0   0  19 953   8   5   2   8   5]
 [  0   5   1   8 113 866 