In [1]:
import time

import matplotlib.pyplot as plt 
import numpy as np 
import os 
import pandas as pd 
import seaborn as sns

In [2]:
train_images = np.load("Kannada_MNIST_npz/Kannada_MNIST/X_kannada_MNIST_train.npz")['arr_0']
test_images = np.load("Kannada_MNIST_npz/Kannada_MNIST/X_kannada_MNIST_test.npz")['arr_0']
train_labels = np.load("Kannada_MNIST_npz/Kannada_MNIST/y_kannada_MNIST_train.npz")['arr_0']
test_labels = np.load("Kannada_MNIST_npz/Kannada_MNIST/y_kannada_MNIST_test.npz")['arr_0']

In [3]:
import tensorflow.keras as keras
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras import backend as K

In [4]:
img_rows, img_cols = 28, 28
batch_size = 128
number_of_samples = 60000
num_classes = 10
epochs = 10

In [5]:
x_train = np.expand_dims(train_images, axis=-1)
x_test = np.expand_dims(test_images, axis=-1)
y_train = keras.utils.to_categorical(train_labels)
y_test = keras.utils.to_categorical(test_labels)
images = np.load("Kannada_MNIST_npz/Dig_MNIST/X_dig_MNIST.npz")['arr_0']
labels = np.load("Kannada_MNIST_npz/Dig_MNIST/y_dig_MNIST.npz")['arr_0']
x_digi_test = np.expand_dims(images, axis=-1)
y_digi_test = keras.utils.to_categorical(labels)

In [6]:
from keras.preprocessing.image import ImageDataGenerator
datagen = ImageDataGenerator(shear_range = 0.5)
it = datagen.flow(x_train, y_train, batch_size=batch_size, classmode)

Using TensorFlow backend.


In [7]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(img_rows, img_cols, 1)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [8]:
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adam(),
              metrics=['accuracy'])

model.fit_generator(it,
          steps_per_epoch = number_of_samples//batch_size,
          epochs=epochs,
          verbose=1,
        )

Epoch 1/10
468/468 [==============================] - 9s 19ms/step - loss: 0.6530 - acc: 0.8574
Epoch 2/10
468/468 [==============================] - 8s 17ms/step - loss: 0.0998 - acc: 0.9701
Epoch 3/10
468/468 [==============================] - 8s 18ms/step - loss: 0.0727 - acc: 0.9788
Epoch 4/10
468/468 [==============================] - 9s 20ms/step - loss: 0.0582 - acc: 0.9829
Epoch 5/10
468/468 [==============================] - 10s 21ms/step - loss: 0.0499 - acc: 0.9848
Epoch 6/10
468/468 [==============================] - 11s 23ms/step - loss: 0.0443 - acc: 0.9867
Epoch 7/10
468/468 [==============================] - 12s 25ms/step - loss: 0.0455 - acc: 0.9868
Epoch 8/10
468/468 [==============================] - 12s 25ms/step - loss: 0.0400 - acc: 0.9884
Epoch 9/10
468/468 [==============================] - 13s 27ms/step - loss: 0.0345 - acc: 0.9896
Epoch 10/10
468/468 [==============================] - 13s 28ms/step - loss: 0.0333 - acc: 0.9899


In [11]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

y_test_pred = model.predict(x_test, batch_size=32, verbose=1)
predicted = np.argmax(y_test_pred, axis=1)
report = classification_report(np.argmax(y_test, axis=1), predicted, digits = 4)
confusion_matrix = confusion_matrix(y_true=np.argmax(y_test, axis=1), y_pred=predicted)
print(report)
print(confusion_matrix)

10000/10000 [==============================] - 0s 49us/sample
              precision    recall  f1-score   support

           0     0.9807    0.9140    0.9462      1000
           1     0.9212    0.9930    0.9557      1000
           2     0.9911    0.9970    0.9940      1000
           3     0.9779    0.9730    0.9754      1000
           4     0.9660    0.9950    0.9803      1000
           5     0.9928    0.9670    0.9797      1000
           6     0.9604    0.9690    0.9647      1000
           7     0.9936    0.9340    0.9629      1000
           8     0.9900    0.9910    0.9905      1000
           9     0.9633    0.9970    0.9799      1000

    accuracy                         0.9730     10000
   macro avg     0.9737    0.9730    0.9729     10000
weighted avg     0.9737    0.9730    0.9729     10000

[[914  78   0   4   0   0   0   0   3   1]
 [  0 993   0   5   0   0   0   0   1   1]
 [  3   0 997   0   0   0   0   0   0   0]
 [  4   5   4 973   1   5   3   5   0   0]
 [  0  

In [12]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

y_digi_pred = model.predict(x_digi_test, batch_size=32, verbose=1)
predicted = np.argmax(y_digi_pred, axis=1)
report = classification_report(np.argmax(y_digi_test, axis=1), predicted, digits = 4)
confusion_matrix = confusion_matrix(y_true=np.argmax(y_digi_test, axis=1), y_pred=predicted)
print(report)
print(confusion_matrix)

10240/10240 [==============================] - 0s 49us/sample
              precision    recall  f1-score   support

           0     0.8408    0.6445    0.7297      1024
           1     0.9418    0.7900    0.8593      1024
           2     0.6949    0.9629    0.8072      1024
           3     0.9330    0.6934    0.7955      1024
           4     0.8896    0.7949    0.8396      1024
           5     0.8899    0.9160    0.9028      1024
           6     0.5474    0.7842    0.6447      1024
           7     0.8315    0.6553    0.7329      1024
           8     0.8483    0.7480    0.7950      1024
           9     0.7386    0.9160    0.8178      1024

    accuracy                         0.7905     10240
   macro avg     0.8156    0.7905    0.7925     10240
weighted avg     0.8156    0.7905    0.7925     10240

[[660  24  46  23   2   9 101   9  29 121]
 [ 98 809  42  12   5  18   2  20   4  14]
 [  6   2 986   1   0   5  15   3   1   5]
 [  9   2 191 710   5  33  36  33   3   2]
 [  3  

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

pred = model.predict(x_test, batch_size=32, verbose=1)
predicted = np.argmax(pred, axis=1)
report = classification_report(np.argmax(y_test, axis=1), predicted, digits = 4)
confusion_matrix = confusion_matrix(y_true=np.argmax(y_test, axis=1), y_pred=predicted)
print(report)
print(confusion_matrix)

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

pred = model.predict(x_digi_test, batch_size=32, verbose=1)
predicted = np.argmax(pred, axis=1)
report = classification_report(np.argmax(y_digi_test, axis=1), predicted, digits = 4)
confusion_matrix = confusion_matrix(y_true=np.argmax(y_digi_test, axis=1), y_pred=np.argmax(pred, axis=1))
print(report)
print(confusion_matrix)

In [ ]:
#plot_cm(np.argmax(y_digi_test, axis=1), np.argmax(pred, axis=1))

In [ ]:
print(model.summary())

In [ ]:
from sklearn.metrics import confusion_matrix

pred = model.predict(x_test, batch_size=32, verbose=1)
predicted = np.argmax(pred, axis=1)
confusion_matrix = confusion_matrix(y_true=np.argmax(y_test, axis=1), y_pred=predicted)

In [ ]:
print(confusion_matrix)